---
Name: everydatastore-logging
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      MailHandler: [ pushHandler, [ '%$MailHandler' ] ]
      LogFileHandler: [ pushHandler, [ '%$LogFileHandler' ] ]
  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "/var/www/app/log/silverstripe.log"
  MailHandler:
      class: Monolog\Handler\NativeMailerHandler
      constructor:
        - office@everydatastore.com
        - There was an error on your test site
        - office@everydatastore.com
        - error
        - info
      properties:
        ContentType: text/html
        Formatter: '%$SilverStripe\Logging\DetailedErrorFormatter'
        